name: ddp
channels:
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - matplotlib
  - scipy
  - pandas
  - numba
  - numpy
  - seaborn 

  - pytest
  - pytest-cov
  - python=3.8
  - python-graphviz

  - virtualenv=20.0.33




