name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
           miniconda-version: "latest"
           activate-environment: ddp
           environment-file: environment.yml
           python-version: 3.8
           auto-activate-base: false
    - name: execute notebooks
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        conda activate ddp
        jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 main_notebook.ipynb
      
